name: Check Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-22.04
    steps:
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrappers: false

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}


      - name : Terraform Init
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: |
          terraform init
      
      - name: Terraform Validate
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: terraform validate
      
      - name: Terraform Plan
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: terraform plan -out plan