name: Check Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Validate and Plan Terraform
    uses: ./.github/workflows/workflow-terraform.yml
    with:
      run_apply: false
    permissions:
      pull-requests: write
      id-token: write
      contents: read
    # secrets: inherit