name: Release

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Apply Terraform
    uses: ./.github/workflows/workflow-terraform.yml
    with:
      run_apply: true
    permissions:
      pull-requests: write
      id-token: write
      contents: read

  